export const VEILD_GIFTS_ABI = [
  { inputs: [{ internalType: "address", name: "_registry", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "IncorrectValue", type: "error" },
  { inputs: [], name: "InvalidGiftType", type: "error" },
  { inputs: [], name: "MessageTooLong", type: "error" },
  { inputs: [], name: "NoEarnings", type: "error" },
  { inputs: [], name: "NotRegistered", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "ZeroPrice", type: "error" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "creator", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "EarningsClaimed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "creator", type: "address" }, { indexed: true, internalType: "address", name: "sender", type: "address" }, { indexed: true, internalType: "uint256", name: "giftTypeId", type: "uint256" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "GiftSent", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: false, internalType: "string", name: "name", type: "string" }, { indexed: false, internalType: "uint256", name: "price", type: "uint256" }], name: "GiftTypeAdded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: false, internalType: "uint256", name: "newPrice", type: "uint256" }, { indexed: false, internalType: "bool", name: "active", type: "bool" }], name: "GiftTypeUpdated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Paused", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Unpaused", type: "event" },
  { inputs: [], name: "BPS_BASE", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "MAX_GIFTS_STORED", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "MAX_MESSAGE_LEN", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "PLATFORM_FEE_BPS", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "string", name: "name", type: "string" }, { internalType: "uint256", name: "price", type: "uint256" }], name: "addGiftType", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "claimEarnings", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "earnings", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "feeRecipient", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "id", type: "uint256" }], name: "getGiftType", outputs: [{ components: [{ internalType: "string", name: "name", type: "string" }, { internalType: "uint256", name: "price", type: "uint256" }, { internalType: "bool", name: "active", type: "bool" }], internalType: "struct VeildGifts.GiftType", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "creator", type: "address" }], name: "getGifts", outputs: [{ components: [{ internalType: "address", name: "sender", type: "address" }, { internalType: "uint256", name: "giftTypeId", type: "uint256" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "uint256", name: "sentAt", type: "uint256" }, { internalType: "string", name: "message", type: "string" }], internalType: "struct VeildGifts.GiftRecord[]", name: "", type: "tuple[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "giftTypeCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "registry", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "creator", type: "address" }, { internalType: "uint256", name: "giftTypeId", type: "uint256" }, { internalType: "string", name: "message", type: "string" }], name: "sendGift", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "address", name: "newRecipient", type: "address" }], name: "setFeeRecipient", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "uint256", name: "newPrice", type: "uint256" }, { internalType: "bool", name: "active", type: "bool" }], name: "updateGiftType", outputs: [], stateMutability: "nonpayable", type: "function" },
] as const;
