export const VEILD_REFERRAL_ABI = [
  { inputs: [{ internalType: "address", name: "_registry", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AlreadyReferred", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "InsufficientFunds", type: "error" },
  { inputs: [], name: "NoRewardPending", type: "error" },
  { inputs: [], name: "NotRegistered", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "ReferrerNotRegistered", type: "error" },
  { inputs: [], name: "SelfReferral", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Paused", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "referrer", type: "address" }, { indexed: true, internalType: "address", name: "referred", type: "address" }], name: "ReferralRecorded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "referrer", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "RewardClaimed", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Unpaused", type: "event" },
  { inputs: [], name: "REWARD_PER_REFERRAL", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "claimReward", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "referred", type: "address" }], name: "getReferrer", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "referrer", type: "address" }], name: "getStats", outputs: [{ components: [{ internalType: "uint256", name: "totalReferrals", type: "uint256" }, { internalType: "uint256", name: "pendingReward", type: "uint256" }, { internalType: "uint256", name: "claimedReward", type: "uint256" }], internalType: "struct VeildReferral.ReferrerStats", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "hasBeenReferred", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "referrer", type: "address" }, { internalType: "address", name: "referred", type: "address" }], name: "recordReferral", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "registry", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "totalReferrals", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }], name: "withdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { stateMutability: "payable", type: "receive" },
] as const;
