/**
 * Veild deployment script
 *
 * Usage:
 *   npx hardhat run scripts/deploy.ts                          # localhost
 *   npx hardhat run scripts/deploy.ts --network celo-sepolia   # testnet
 *   npx hardhat run scripts/deploy.ts --network celo           # mainnet
 *
 * What this script does:
 *   1. Pre-flight: prints network, deployer, and balance
 *   2. Requires confirmation before deploying to mainnet
 *   3. Deploys VeildRegistry then VeildMessages (in dependency order)
 *   4. Saves full deployment info → deployments/{network}.json
 *   5. Writes deployments/addresses.ts so the frontend can import typed addresses
 *   6. On live networks: waits for 5 block confirmations then auto-verifies on Celoscan
 */

import hre from "hardhat";
import { formatEther } from "viem";
import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function log(msg: string) {
  console.log(msg);
}

function separator() {
  log("─".repeat(60));
}

async function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(`${question} [y/N] `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === "y");
    });
  });
}

function saveDeployment(
  networkName: string,
  chainId: number | undefined,
  deployer: string,
  registry: string,
  messaging: string
) {
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });

  const info = {
    network: networkName,
    chainId: chainId ?? 0,
    timestamp: new Date().toISOString(),
    deployer,
    contracts: {
      VeildRegistry: registry,
      VeildMessages: messaging,
    },
  };

  // ── deployments/{network}.json ────────────────────────────────────────────
  const jsonPath = path.join(deploymentsDir, `${networkName}.json`);
  fs.writeFileSync(jsonPath, JSON.stringify(info, null, 2));
  log(`\nSaved deployment info → ${jsonPath}`);

  // ── deployments/addresses.ts  (frontend import) ───────────────────────────
  const indexPath = path.join(deploymentsDir, "addresses.ts");
  const existing: Record<string, { VeildRegistry: string; VeildMessages: string }> =
    fs.existsSync(indexPath)
      ? JSON.parse(
          fs
            .readFileSync(indexPath, "utf-8")
            .replace(/^.*?=\s*/s, "")   // strip "export const ... ="
            .replace(/\s*as const.*$/s, "")
        )
      : {};

  existing[networkName] = {
    VeildRegistry: registry,
    VeildMessages: messaging,
  };

  const tsContent =
    `// Auto-generated by scripts/deploy.ts — DO NOT EDIT\n` +
    `export const CONTRACT_ADDRESSES = ${JSON.stringify(existing, null, 2)} as const;\n` +
    `\n` +
    `export type NetworkName = keyof typeof CONTRACT_ADDRESSES;\n`;

  fs.writeFileSync(indexPath, tsContent);
  log(`Updated contract addresses → ${indexPath}`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const networkName = hre.network.name;
  const isLiveNetwork = networkName !== "localhost" && networkName !== "hardhat";

  separator();
  log("  🪄  Veild — Contract Deployment");
  separator();

  // ── 1. Pre-flight ─────────────────────────────────────────────────────────
  const [deployer] = await hre.viem.getWalletClients();
  const publicClient = await hre.viem.getPublicClient();
  const deployerAddress = deployer.account.address;
  const balance = await publicClient.getBalance({ address: deployerAddress });
  const chainId = await publicClient.getChainId();

  log(`  Network   : ${networkName} (chainId ${chainId})`);
  log(`  Deployer  : ${deployerAddress}`);
  log(`  Balance   : ${formatEther(balance)} CELO`);
  separator();

  if (balance === 0n) {
    throw new Error("❌  Deployer has zero balance — fund the account first.");
  }

  // ── 2. Mainnet confirmation ───────────────────────────────────────────────
  if (networkName === "celo") {
    const ok = await confirm(
      "\n⚠️   You are deploying to CELO MAINNET. Continue?"
    );
    if (!ok) {
      log("Aborted.");
      process.exit(0);
    }
  }

  // ── 3. Deploy VeildRegistry ───────────────────────────────────────────────
  log("\n[1/2] Deploying VeildRegistry...");

  const registry = await hre.viem.deployContract("VeildRegistry");
  const registryTx = registry.deploymentTransaction?.();

  log(`  ✔  VeildRegistry deployed`);
  log(`     Address : ${registry.address}`);
  if (registryTx) log(`     Tx hash : ${registryTx.hash}`);

  // ── 4. Deploy VeildMessages ───────────────────────────────────────────────
  log("\n[2/2] Deploying VeildMessages...");

  const messaging = await hre.viem.deployContract("VeildMessages", [
    registry.address,
  ]);
  const messagingTx = messaging.deploymentTransaction?.();

  log(`  ✔  VeildMessages deployed`);
  log(`     Address : ${messaging.address}`);
  if (messagingTx) log(`     Tx hash : ${messagingTx.hash}`);

  // ── 5. Persist addresses ──────────────────────────────────────────────────
  saveDeployment(
    networkName,
    chainId,
    deployerAddress,
    registry.address,
    messaging.address
  );

  // ── 6. Verify on live networks ────────────────────────────────────────────
  if (isLiveNetwork) {
    log("\nWaiting for 5 block confirmations before verifying...");
    if (registryTx?.hash) {
      await publicClient.waitForTransactionReceipt({
        hash: registryTx.hash,
        confirmations: 5,
      });
    }
    if (messagingTx?.hash) {
      await publicClient.waitForTransactionReceipt({
        hash: messagingTx.hash,
        confirmations: 5,
      });
    }

    log("\nVerifying VeildRegistry on Celoscan...");
    await hre
      .run("verify:verify", {
        address: registry.address,
        constructorArguments: [],
      })
      .catch((e: Error) => {
        if (e.message.includes("Already Verified")) {
          log("  ℹ  Already verified.");
        } else {
          log(`  ⚠  Verification failed: ${e.message}`);
        }
      });

    log("Verifying VeildMessages on Celoscan...");
    await hre
      .run("verify:verify", {
        address: messaging.address,
        constructorArguments: [registry.address],
      })
      .catch((e: Error) => {
        if (e.message.includes("Already Verified")) {
          log("  ℹ  Already verified.");
        } else {
          log(`  ⚠  Verification failed: ${e.message}`);
        }
      });
  }

  // ── 7. Summary ────────────────────────────────────────────────────────────
  separator();
  log("  ✅  Deployment complete!");
  separator();
  console.table({
    VeildRegistry: registry.address,
    VeildMessages: messaging.address,
  });

  if (isLiveNetwork) {
    const explorerBase =
      networkName === "celo"
        ? "https://celoscan.io/address/"
        : "https://alfajores.celoscan.io/address/";

    log(
      `\n  Registry  : ${explorerBase}${registry.address}`
    );
    log(
      `  Messaging : ${explorerBase}${messaging.address}`
    );
  }
  separator();
}

main().catch((error) => {
  console.error("\n❌  Deployment failed:", error.message ?? error);
  process.exitCode = 1;
});
