/**
 * Veild deployment script
 *
 * Usage:
 *   npx hardhat run scripts/deploy.ts                          # localhost
 *   npx hardhat run scripts/deploy.ts --network celo-sepolia   # testnet
 *   npx hardhat run scripts/deploy.ts --network celo           # mainnet
 *
 * What this script does:
 *   1. Pre-flight: prints network, deployer, and balance
 *   2. Requires confirmation before deploying to mainnet
 *   3. Deploys all 6 contracts in dependency order
 *   4. Saves full deployment info → deployments/{network}.json
 *   5. Writes deployments/addresses.ts so the frontend can import typed addresses
 *   6. On live networks: waits for 5 block confirmations then auto-verifies on Celoscan
 */

import hre from "hardhat";
import { formatEther } from "viem";
import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function log(msg: string) {
  console.log(msg);
}

function separator() {
  log("─".repeat(60));
}

async function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(`${question} [y/N] `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === "y");
    });
  });
}

interface ContractAddresses {
  VeildRegistry: string;
  VeildMessages: string;
  VeildTips: string;
  VeildSubscriptions: string;
  VeildPools: string;
  VeildBadges: string;
}

function saveDeployment(
  networkName: string,
  chainId: number | undefined,
  deployer: string,
  addrs: ContractAddresses
) {
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });

  const info = {
    network: networkName,
    chainId: chainId ?? 0,
    timestamp: new Date().toISOString(),
    deployer,
    contracts: addrs,
  };

  // ── deployments/{network}.json ────────────────────────────────────────────
  const jsonPath = path.join(deploymentsDir, `${networkName}.json`);
  fs.writeFileSync(jsonPath, JSON.stringify(info, null, 2));
  log(`\nSaved deployment info → ${jsonPath}`);

  // ── deployments/addresses.ts  (frontend import) ───────────────────────────
  const indexPath = path.join(deploymentsDir, "addresses.ts");
  const existing: Record<string, ContractAddresses> = fs.existsSync(indexPath)
    ? JSON.parse(
        fs
          .readFileSync(indexPath, "utf-8")
          .replace(/^.*?=\s*/s, "")
          .replace(/\s*as const.*$/s, "")
      )
    : {};

  existing[networkName] = addrs;

  const tsContent =
    `// Auto-generated by scripts/deploy.ts — DO NOT EDIT\n` +
    `export const CONTRACT_ADDRESSES = ${JSON.stringify(existing, null, 2)} as const;\n` +
    `\n` +
    `export type NetworkName = keyof typeof CONTRACT_ADDRESSES;\n`;

  fs.writeFileSync(indexPath, tsContent);
  log(`Updated contract addresses → ${indexPath}`);
}

async function verifyContract(
  address: string,
  constructorArgs: unknown[],
  name: string
) {
  log(`\nVerifying ${name} on Celoscan...`);
  await hre
    .run("verify:verify", {
      address,
      constructorArguments: constructorArgs,
    })
    .catch((e: Error) => {
      if (e.message.includes("Already Verified")) {
        log(`  ℹ  ${name}: already verified.`);
      } else {
        log(`  ⚠  ${name}: verification failed — ${e.message}`);
      }
    });
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const networkName   = hre.network.name;
  const isLiveNetwork = networkName !== "localhost" && networkName !== "hardhat";

  separator();
  log("  🪄  Veild — Full Contract Deployment");
  separator();

  // ── 1. Pre-flight ─────────────────────────────────────────────────────────
  const [deployer] = await hre.viem.getWalletClients();
  const publicClient   = await hre.viem.getPublicClient();
  const deployerAddress = deployer.account.address;
  const balance        = await publicClient.getBalance({ address: deployerAddress });
  const chainId        = await publicClient.getChainId();

  log(`  Network      : ${networkName} (chainId ${chainId})`);
  log(`  Deployer     : ${deployerAddress}`);
  log(`  Balance      : ${formatEther(balance)} CELO`);
  separator();

  if (balance === 0n) {
    throw new Error("❌  Deployer has zero balance — fund the account first.");
  }

  // ── 2. Mainnet confirmation ───────────────────────────────────────────────
  if (networkName === "celo") {
    const ok = await confirm("\n⚠️   You are deploying to CELO MAINNET. Continue?");
    if (!ok) {
      log("Aborted.");
      process.exit(0);
    }
  }

  // ── 3. Deploy VeildRegistry ───────────────────────────────────────────────
  log("\n[1/5] Deploying VeildRegistry...");
  const registry = await hre.viem.deployContract("VeildRegistry");
  log(`  ✔  VeildRegistry  → ${registry.address}`);

  // ── 4. Deploy VeildMessages ───────────────────────────────────────────────
  log("\n[2/5] Deploying VeildMessages...");
  const messaging = await hre.viem.deployContract("VeildMessages", [registry.address]);
  log(`  ✔  VeildMessages  → ${messaging.address}`);

  // ── 5. Deploy VeildTips ───────────────────────────────────────────────────
  log("\n[3/5] Deploying VeildTips...");
  const tips = await hre.viem.deployContract("VeildTips", [registry.address]);
  log(`  ✔  VeildTips      → ${tips.address}`);

  // ── 6. Deploy VeildSubscriptions ─────────────────────────────────────────
  log("\n[4/5] Deploying VeildSubscriptions...");
  const subscriptions = await hre.viem.deployContract("VeildSubscriptions", [registry.address]);
  log(`  ✔  VeildSubscriptions → ${subscriptions.address}`);

  // ── 7. Deploy VeildPools ──────────────────────────────────────────────────
  log("\n[5/6] Deploying VeildPools...");
  const pools = await hre.viem.deployContract("VeildPools", [registry.address]);
  log(`  ✔  VeildPools     → ${pools.address}`);

  // ── 8. Deploy VeildBadges ─────────────────────────────────────────────────
  log("\n[6/6] Deploying VeildBadges...");
  const badges = await hre.viem.deployContract("VeildBadges");
  log(`  ✔  VeildBadges    → ${badges.address}`);

  // ── 9. Persist addresses ──────────────────────────────────────────────────
  const addrs: ContractAddresses = {
    VeildRegistry:      registry.address,
    VeildMessages:      messaging.address,
    VeildTips:          tips.address,
    VeildSubscriptions: subscriptions.address,
    VeildPools:         pools.address,
    VeildBadges:        badges.address,
  };
  saveDeployment(networkName, chainId, deployerAddress, addrs);

  // ── 10. Verify on live networks ───────────────────────────────────────────
  if (isLiveNetwork) {
    log("\nWaiting for 5 block confirmations...");
    for (const c of [registry, messaging, tips, subscriptions, pools, badges]) {
      const tx = c.deploymentTransaction?.();
      if (tx?.hash) {
        await publicClient.waitForTransactionReceipt({ hash: tx.hash, confirmations: 5 });
      }
    }

    await verifyContract(registry.address,      [],                       "VeildRegistry");
    await verifyContract(messaging.address,     [registry.address],        "VeildMessages");
    await verifyContract(tips.address,          [registry.address],        "VeildTips");
    await verifyContract(subscriptions.address, [registry.address],        "VeildSubscriptions");
    await verifyContract(pools.address,         [registry.address],        "VeildPools");
    await verifyContract(badges.address,        [],                        "VeildBadges");
  }

  // ── 11. Summary ───────────────────────────────────────────────────────────
  separator();
  log("  ✅  Deployment complete!");
  separator();
  console.table(addrs);

  if (isLiveNetwork) {
    const explorerBase =
      networkName === "celo"
        ? "https://celoscan.io/address/"
        : "https://alfajores.celoscan.io/address/";

    for (const [name, addr] of Object.entries(addrs)) {
      log(`  ${name.padEnd(20)}: ${explorerBase}${addr}`);
    }
  }
  separator();
}

main().catch((error) => {
  console.error("\n❌  Deployment failed:", error.message ?? error);
  process.exitCode = 1;
});
